import type { PoemType } from './poem-types';

export interface LayoutMode {
  id: string;
  name: string;
  titleColStart: number;
  titleColSpan: number;
  titleRowStart: number;
  titleRowSpan: number;
  titleSize: 'var(--type-display)' | 'var(--type-hero)' | 'var(--type-title)';
  titleAlign: 'left' | 'right' | 'center';
  bodyColStart: number;
  bodyColSpan: number;
  bodyRowStart: number;
  metaCorner: 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right';
  accentTarget: 'title' | 'first-line' | 'meta' | 'none';
  whiteRatio: number;
  validFor: PoemType[];
  seedAdjustable: ('titleRowStart' | 'bodyRowStart' | 'titleColStart')[];
}

export const layoutModes: LayoutMode[] = [
  {
    id: 'DL-01',
    name: 'left-press-right-flow',
    titleColStart: 1,
    titleColSpan: 8,
    titleRowStart: 1,
    titleRowSpan: 3,
    titleSize: 'var(--type-hero)',
    titleAlign: 'left',
    bodyColStart: 10,
    bodyColSpan: 13,
    bodyRowStart: 1,
    metaCorner: 'bottom-right',
    accentTarget: 'title',
    whiteRatio: 0.05,
    validFor: ['dense-linear', 'prose-lyric', 'lyric-dense'],
    seedAdjustable: ['titleRowStart'],
  },
  {
    id: 'DL-02',
    name: 'right-press-left-flow',
    titleColStart: 17,
    titleColSpan: 8,
    titleRowStart: 1,
    titleRowSpan: 3,
    titleSize: 'var(--type-hero)',
    titleAlign: 'left',
    bodyColStart: 1,
    bodyColSpan: 13,
    bodyRowStart: 1,
    metaCorner: 'bottom-left',
    accentTarget: 'first-line',
    whiteRatio: 0.05,
    validFor: ['dense-linear', 'prose-lyric', 'lyric-dense'],
    seedAdjustable: ['titleRowStart'],
  },
  {
    id: 'DL-03',
    name: 'top-anchor-full',
    titleColStart: 1,
    titleColSpan: 21,
    titleRowStart: 1,
    titleRowSpan: 2,
    titleSize: 'var(--type-display)',
    titleAlign: 'left',
    bodyColStart: 4,
    bodyColSpan: 13,
    bodyRowStart: 4,
    metaCorner: 'top-right',
    accentTarget: 'meta',
    whiteRatio: 0.1,
    validFor: ['dense-linear', 'prose-lyric', 'structured', 'hymn-structured'],
    seedAdjustable: ['bodyRowStart'],
  },
  {
    id: 'DL-04',
    name: 'full-width-press',
    titleColStart: 1,
    titleColSpan: 21,
    titleRowStart: 2,
    titleRowSpan: 3,
    titleSize: 'var(--type-hero)',
    titleAlign: 'left',
    bodyColStart: 6,
    bodyColSpan: 13,
    bodyRowStart: 6,
    metaCorner: 'top-left',
    accentTarget: 'none',
    whiteRatio: 0.08,
    validFor: ['dense-linear', 'lyric-dense', 'prose-lyric'],
    seedAdjustable: ['titleRowStart', 'bodyRowStart'],
  },
  {
    id: 'DL-05',
    name: 'dual-column-body',
    titleColStart: 1,
    titleColSpan: 21,
    titleRowStart: 1,
    titleRowSpan: 2,
    titleSize: 'var(--type-display)',
    titleAlign: 'center',
    bodyColStart: 1,
    bodyColSpan: 21,
    bodyRowStart: 4,
    metaCorner: 'bottom-right',
    accentTarget: 'first-line',
    whiteRatio: 0.05,
    validFor: ['prose-lyric', 'dense-linear'],
    seedAdjustable: [],
  },
  {
    id: 'ST-01',
    name: 'left-narrow-right-wide',
    titleColStart: 1,
    titleColSpan: 5,
    titleRowStart: 1,
    titleRowSpan: 2,
    titleSize: 'var(--type-display)',
    titleAlign: 'left',
    bodyColStart: 7,
    bodyColSpan: 13,
    bodyRowStart: 1,
    metaCorner: 'bottom-left',
    accentTarget: 'title',
    whiteRatio: 0.15,
    validFor: ['structured', 'structured-repetitive', 'hymn-structured', 'meditative'],
    seedAdjustable: ['titleRowStart'],
  },
  {
    id: 'ST-02',
    name: 'right-narrow-left-wide',
    titleColStart: 19,
    titleColSpan: 5,
    titleRowStart: 1,
    titleRowSpan: 2,
    titleSize: 'var(--type-display)',
    titleAlign: 'left',
    bodyColStart: 1,
    bodyColSpan: 13,
    bodyRowStart: 1,
    metaCorner: 'bottom-right',
    accentTarget: 'meta',
    whiteRatio: 0.15,
    validFor: ['structured', 'structured-repetitive', 'hymn-structured', 'meditative'],
    seedAdjustable: ['titleRowStart'],
  },
  {
    id: 'ST-03',
    name: 'center-axis',
    titleColStart: 5,
    titleColSpan: 13,
    titleRowStart: 1,
    titleRowSpan: 2,
    titleSize: 'var(--type-display)',
    titleAlign: 'center',
    bodyColStart: 8,
    bodyColSpan: 8,
    bodyRowStart: 4,
    metaCorner: 'bottom-left',
    accentTarget: 'none',
    whiteRatio: 0.25,
    validFor: ['structured', 'hymn-structured', 'meditative', 'still-observation'],
    seedAdjustable: ['bodyRowStart'],
  },
  {
    id: 'ST-04',
    name: 'staggered-alternating',
    titleColStart: 3,
    titleColSpan: 8,
    titleRowStart: 1,
    titleRowSpan: 2,
    titleSize: 'var(--type-title)',
    titleAlign: 'left',
    bodyColStart: 1,
    bodyColSpan: 21,
    bodyRowStart: 4,
    metaCorner: 'top-right',
    accentTarget: 'first-line',
    whiteRatio: 0.1,
    validFor: ['structured', 'structured-repetitive', 'hymn-structured'],
    seedAdjustable: ['titleColStart', 'bodyRowStart'],
  },
  {
    id: 'IN-01',
    name: 'incant-left-column',
    titleColStart: 1,
    titleColSpan: 3,
    titleRowStart: 1,
    titleRowSpan: 5,
    titleSize: 'var(--type-hero)',
    titleAlign: 'left',
    bodyColStart: 5,
    bodyColSpan: 13,
    bodyRowStart: 1,
    metaCorner: 'bottom-right',
    accentTarget: 'title',
    whiteRatio: 0.2,
    validFor: ['incantatory', 'structured-repetitive'],
    seedAdjustable: ['bodyRowStart'],
  },
  {
    id: 'IN-02',
    name: 'incant-top-press',
    titleColStart: 1,
    titleColSpan: 13,
    titleRowStart: 1,
    titleRowSpan: 2,
    titleSize: 'var(--type-hero)',
    titleAlign: 'left',
    bodyColStart: 1,
    bodyColSpan: 8,
    bodyRowStart: 4,
    metaCorner: 'bottom-right',
    accentTarget: 'first-line',
    whiteRatio: 0.3,
    validFor: ['incantatory', 'structured-repetitive', 'minimal-aphoristic'],
    seedAdjustable: ['bodyRowStart'],
  },
  {
    id: 'IN-03',
    name: 'incant-wide-breathing',
    titleColStart: 4,
    titleColSpan: 8,
    titleRowStart: 3,
    titleRowSpan: 2,
    titleSize: 'var(--type-display)',
    titleAlign: 'left',
    bodyColStart: 4,
    bodyColSpan: 13,
    bodyRowStart: 6,
    metaCorner: 'top-left',
    accentTarget: 'none',
    whiteRatio: 0.35,
    validFor: ['incantatory', 'meditative', 'still-observation'],
    seedAdjustable: ['titleRowStart', 'bodyRowStart'],
  },
  {
    id: 'MN-01',
    name: 'diagonal-top-left',
    titleColStart: 1,
    titleColSpan: 8,
    titleRowStart: 1,
    titleRowSpan: 2,
    titleSize: 'var(--type-hero)',
    titleAlign: 'left',
    bodyColStart: 14,
    bodyColSpan: 8,
    bodyRowStart: 7,
    metaCorner: 'bottom-left',
    accentTarget: 'none',
    whiteRatio: 0.55,
    validFor: ['minimal-fragment', 'minimal-aphoristic', 'still-observation', 'lyric-fragmented'],
    seedAdjustable: [],
  },
  {
    id: 'MN-02',
    name: 'diagonal-top-right',
    titleColStart: 14,
    titleColSpan: 8,
    titleRowStart: 1,
    titleRowSpan: 2,
    titleSize: 'var(--type-hero)',
    titleAlign: 'left',
    bodyColStart: 1,
    bodyColSpan: 8,
    bodyRowStart: 7,
    metaCorner: 'bottom-right',
    accentTarget: 'first-line',
    whiteRatio: 0.55,
    validFor: ['minimal-fragment', 'minimal-aphoristic', 'still-observation'],
    seedAdjustable: [],
  },
  {
    id: 'MN-03',
    name: 'island-center',
    titleColStart: 6,
    titleColSpan: 13,
    titleRowStart: 3,
    titleRowSpan: 2,
    titleSize: 'var(--type-display)',
    titleAlign: 'center',
    bodyColStart: 9,
    bodyColSpan: 8,
    bodyRowStart: 6,
    metaCorner: 'bottom-right',
    accentTarget: 'meta',
    whiteRatio: 0.5,
    validFor: ['minimal-fragment', 'minimal-aphoristic', 'meditative', 'still-observation'],
    seedAdjustable: ['titleRowStart'],
  },
  {
    id: 'MN-04',
    name: 'bottom-sink',
    titleColStart: 1,
    titleColSpan: 13,
    titleRowStart: 7,
    titleRowSpan: 2,
    titleSize: 'var(--type-display)',
    titleAlign: 'left',
    bodyColStart: 3,
    bodyColSpan: 8,
    bodyRowStart: 4,
    metaCorner: 'top-right',
    accentTarget: 'none',
    whiteRatio: 0.45,
    validFor: ['minimal-fragment', 'minimal-aphoristic', 'meditative'],
    seedAdjustable: [],
  },
  {
    id: 'MN-05',
    name: 'left-edge',
    titleColStart: 1,
    titleColSpan: 3,
    titleRowStart: 1,
    titleRowSpan: 3,
    titleSize: 'var(--type-hero)',
    titleAlign: 'left',
    bodyColStart: 1,
    bodyColSpan: 5,
    bodyRowStart: 5,
    metaCorner: 'bottom-right',
    accentTarget: 'title',
    whiteRatio: 0.6,
    validFor: ['minimal-fragment', 'still-observation', 'minimal-aphoristic'],
    seedAdjustable: ['bodyRowStart'],
  },
  {
    id: 'MN-06',
    name: 'right-edge',
    titleColStart: 20,
    titleColSpan: 5,
    titleRowStart: 1,
    titleRowSpan: 3,
    titleSize: 'var(--type-hero)',
    titleAlign: 'left',
    bodyColStart: 16,
    bodyColSpan: 8,
    bodyRowStart: 5,
    metaCorner: 'bottom-left',
    accentTarget: 'first-line',
    whiteRatio: 0.6,
    validFor: ['minimal-fragment', 'still-observation'],
    seedAdjustable: ['bodyRowStart'],
  },
  {
    id: 'LF-01',
    name: 'fragment-scatter-left',
    titleColStart: 2,
    titleColSpan: 8,
    titleRowStart: 2,
    titleRowSpan: 2,
    titleSize: 'var(--type-display)',
    titleAlign: 'left',
    bodyColStart: 13,
    bodyColSpan: 8,
    bodyRowStart: 3,
    metaCorner: 'top-right',
    accentTarget: 'first-line',
    whiteRatio: 0.35,
    validFor: ['lyric-fragmented', 'hybrid', 'lyric-dense'],
    seedAdjustable: ['titleRowStart', 'bodyRowStart'],
  },
  {
    id: 'LF-02',
    name: 'fragment-scatter-right',
    titleColStart: 14,
    titleColSpan: 8,
    titleRowStart: 2,
    titleRowSpan: 2,
    titleSize: 'var(--type-display)',
    titleAlign: 'left',
    bodyColStart: 1,
    bodyColSpan: 8,
    bodyRowStart: 3,
    metaCorner: 'top-left',
    accentTarget: 'meta',
    whiteRatio: 0.35,
    validFor: ['lyric-fragmented', 'hybrid'],
    seedAdjustable: ['titleRowStart', 'bodyRowStart'],
  },
  {
    id: 'LF-03',
    name: 'lyric-tension',
    titleColStart: 1,
    titleColSpan: 5,
    titleRowStart: 4,
    titleRowSpan: 3,
    titleSize: 'var(--type-hero)',
    titleAlign: 'left',
    bodyColStart: 8,
    bodyColSpan: 13,
    bodyRowStart: 1,
    metaCorner: 'bottom-right',
    accentTarget: 'title',
    whiteRatio: 0.2,
    validFor: ['lyric-fragmented', 'lyric-dense', 'hybrid'],
    seedAdjustable: ['titleRowStart'],
  },
  {
    id: 'DR-01',
    name: 'dramatic-left-stage',
    titleColStart: 1,
    titleColSpan: 8,
    titleRowStart: 1,
    titleRowSpan: 2,
    titleSize: 'var(--type-display)',
    titleAlign: 'left',
    bodyColStart: 1,
    bodyColSpan: 21,
    bodyRowStart: 4,
    metaCorner: 'top-right',
    accentTarget: 'first-line',
    whiteRatio: 0.1,
    validFor: ['dramatic-monologue', 'dramatic-narrative', 'collage'],
    seedAdjustable: ['bodyRowStart'],
  },
  {
    id: 'DR-02',
    name: 'dramatic-split',
    titleColStart: 1,
    titleColSpan: 13,
    titleRowStart: 1,
    titleRowSpan: 2,
    titleSize: 'var(--type-display)',
    titleAlign: 'left',
    bodyColStart: 3,
    bodyColSpan: 13,
    bodyRowStart: 4,
    metaCorner: 'bottom-right',
    accentTarget: 'none',
    whiteRatio: 0.2,
    validFor: ['dramatic-monologue', 'dramatic-narrative', 'hybrid'],
    seedAdjustable: ['titleColStart', 'bodyRowStart'],
  },
  {
    id: 'DR-03',
    name: 'collage-zones',
    titleColStart: 1,
    titleColSpan: 5,
    titleRowStart: 1,
    titleRowSpan: 3,
    titleSize: 'var(--type-title)',
    titleAlign: 'left',
    bodyColStart: 7,
    bodyColSpan: 13,
    bodyRowStart: 1,
    metaCorner: 'bottom-left',
    accentTarget: 'meta',
    whiteRatio: 0.15,
    validFor: ['collage', 'triptych', 'hybrid'],
    seedAdjustable: ['bodyRowStart'],
  },
  {
    id: 'TR-01',
    name: 'triptych-top-label',
    titleColStart: 1,
    titleColSpan: 8,
    titleRowStart: 1,
    titleRowSpan: 1,
    titleSize: 'var(--type-title)',
    titleAlign: 'left',
    bodyColStart: 1,
    bodyColSpan: 21,
    bodyRowStart: 3,
    metaCorner: 'top-right',
    accentTarget: 'meta',
    whiteRatio: 0.1,
    validFor: ['triptych', 'collage', 'structured'],
    seedAdjustable: ['bodyRowStart'],
  },
  {
    id: 'TR-02',
    name: 'triptych-side-label',
    titleColStart: 20,
    titleColSpan: 5,
    titleRowStart: 1,
    titleRowSpan: 2,
    titleSize: 'var(--type-title)',
    titleAlign: 'left',
    bodyColStart: 1,
    bodyColSpan: 17,
    bodyRowStart: 1,
    metaCorner: 'bottom-right',
    accentTarget: 'none',
    whiteRatio: 0.1,
    validFor: ['triptych', 'collage'],
    seedAdjustable: [],
  },
  {
    id: 'MD-01',
    name: 'meditative-breath',
    titleColStart: 3,
    titleColSpan: 8,
    titleRowStart: 2,
    titleRowSpan: 2,
    titleSize: 'var(--type-display)',
    titleAlign: 'left',
    bodyColStart: 5,
    bodyColSpan: 8,
    bodyRowStart: 5,
    metaCorner: 'bottom-right',
    accentTarget: 'none',
    whiteRatio: 0.45,
    validFor: ['meditative', 'still-observation', 'minimal-fragment'],
    seedAdjustable: ['titleRowStart', 'bodyRowStart'],
  },
  {
    id: 'MD-02',
    name: 'still-right-float',
    titleColStart: 14,
    titleColSpan: 8,
    titleRowStart: 3,
    titleRowSpan: 2,
    titleSize: 'var(--type-display)',
    titleAlign: 'left',
    bodyColStart: 16,
    bodyColSpan: 8,
    bodyRowStart: 6,
    metaCorner: 'top-left',
    accentTarget: 'first-line',
    whiteRatio: 0.5,
    validFor: ['still-observation', 'meditative', 'minimal-fragment'],
    seedAdjustable: ['titleRowStart', 'bodyRowStart'],
  },
  {
    id: 'MD-03',
    name: 'still-observation-wide',
    titleColStart: 1,
    titleColSpan: 13,
    titleRowStart: 1,
    titleRowSpan: 2,
    titleSize: 'var(--type-display)',
    titleAlign: 'left',
    bodyColStart: 1,
    bodyColSpan: 13,
    bodyRowStart: 4,
    metaCorner: 'bottom-right',
    accentTarget: 'meta',
    whiteRatio: 0.3,
    validFor: ['still-observation', 'meditative', 'structured'],
    seedAdjustable: ['bodyRowStart'],
  },
  {
    id: 'EX-01',
    name: 'micro-title-macro-body',
    titleColStart: 1,
    titleColSpan: 3,
    titleRowStart: 1,
    titleRowSpan: 1,
    titleSize: 'var(--type-title)',
    titleAlign: 'left',
    bodyColStart: 1,
    bodyColSpan: 21,
    bodyRowStart: 2,
    metaCorner: 'bottom-right',
    accentTarget: 'none',
    whiteRatio: 0.05,
    validFor: ['dense-linear', 'prose-lyric', 'lyric-dense', 'dramatic-narrative'],
    seedAdjustable: [],
  },
  {
    id: 'EX-02',
    name: 'macro-title-micro-body',
    titleColStart: 1,
    titleColSpan: 21,
    titleRowStart: 1,
    titleRowSpan: 5,
    titleSize: 'var(--type-hero)',
    titleAlign: 'left',
    bodyColStart: 14,
    bodyColSpan: 8,
    bodyRowStart: 7,
    metaCorner: 'top-right',
    accentTarget: 'title',
    whiteRatio: 0.15,
    validFor: ['minimal-aphoristic', 'minimal-fragment', 'incantatory'],
    seedAdjustable: [],
  },
  {
    id: 'EX-03',
    name: 'gravity-reverse',
    titleColStart: 1,
    titleColSpan: 13,
    titleRowStart: 8,
    titleRowSpan: 2,
    titleSize: 'var(--type-display)',
    titleAlign: 'left',
    bodyColStart: 3,
    bodyColSpan: 13,
    bodyRowStart: 1,
    metaCorner: 'top-right',
    accentTarget: 'meta',
    whiteRatio: 0.25,
    validFor: ['meditative', 'lyric-fragmented', 'still-observation', 'minimal-fragment'],
    seedAdjustable: [],
  },
  {
    id: 'EX-04',
    name: 'invasion-overlap',
    titleColStart: 1,
    titleColSpan: 13,
    titleRowStart: 1,
    titleRowSpan: 2,
    titleSize: 'var(--type-display)',
    titleAlign: 'left',
    bodyColStart: 9,
    bodyColSpan: 13,
    bodyRowStart: 3,
    metaCorner: 'bottom-left',
    accentTarget: 'first-line',
    whiteRatio: 0.1,
    validFor: ['lyric-dense', 'dense-linear', 'hybrid', 'dramatic-narrative'],
    seedAdjustable: ['bodyRowStart'],
  },
  {
    id: 'EX-05',
    name: 'extreme-whitespace',
    titleColStart: 9,
    titleColSpan: 5,
    titleRowStart: 4,
    titleRowSpan: 2,
    titleSize: 'var(--type-display)',
    titleAlign: 'center',
    bodyColStart: 11,
    bodyColSpan: 5,
    bodyRowStart: 7,
    metaCorner: 'bottom-right',
    accentTarget: 'none',
    whiteRatio: 0.7,
    validFor: ['minimal-aphoristic', 'minimal-fragment', 'still-observation'],
    seedAdjustable: ['titleRowStart'],
  },
  {
    id: 'HY-01',
    name: 'hybrid-split-balance',
    titleColStart: 4,
    titleColSpan: 8,
    titleRowStart: 2,
    titleRowSpan: 2,
    titleSize: 'var(--type-display)',
    titleAlign: 'left',
    bodyColStart: 13,
    bodyColSpan: 8,
    bodyRowStart: 4,
    metaCorner: 'bottom-left',
    accentTarget: 'first-line',
    whiteRatio: 0.28,
    validFor: ['hybrid', 'lyric-fragmented', 'collage'],
    seedAdjustable: ['titleRowStart', 'bodyRowStart'],
  },
];

export function getValidModes(type: PoemType): LayoutMode[] {
  return layoutModes.filter((m) => m.validFor.includes(type));
}
