/** Shared preface copy (print PDF not in repo — same text as /preface). */
export const prefaceParagraphs: string[] = [
  'This collection was written between 2024 and the spring of 2025 — a period of introspection, narrative reconfiguration, and emotional intensity. It coincided with my final year in New York, and possibly my last chapter in America. During this time, I lived alone, gradually withdrawing from interpersonal entanglements. Communication became minimal, yet a growing spiritual dependence surged beneath the surface.',
  'Born in Jiangsu, China, raised in Shanghai, and now writing from New York, I have lived across multiple cities and regions. These displacements have diluted my sense of “home,” turning it into an abstract constellation rather than a fixed location. I have left traces everywhere, but nowhere I fully belong.',
  'When I say Three Worlds, I do not mean three sealed rooms. I mean three pressures that act on the same person at once: the world that watches and sorts you (Their World), the world of others you cannot stop loving (Bless You), and the world of objects, weather, and memory that returns you to your own skin (Still Life). The poems leak across these borders on purpose; the sections are porous because experience is.',
  'English is not the language I was born inside, yet it has become the language in which these poems arrived — partly because of education and migration, partly because of the strange privacy it grants me in public. Chinese still moves underneath, in rhythm, in image, in the way a line refuses to behave. I leave that tension visible rather than translating it away.',
  'The manuscript was assembled while I was moving again — this time toward Brisbane — carrying hard drives, negatives, notebooks, and the habit of writing at odd hours. The work is marked by that transit: alert to surveillance and institutions, hungry for intimacy, stubbornly attached to small sensory facts that prove the world is still real.',
  'I do not offer these poems as testimony in a legal sense. They are closer to weather reports from the interior: sometimes cooled by irony, sometimes overheated, sometimes trying to be precise about damage without turning pain into a spectacle. If a line seems cold, look for where it trembles; if a line seems soft, look for what it is protecting.',
  'Three Worlds is dedicated to the reader willing to read slowly — who understands that a poem can be a machine for adjusting attention, not a message to be consumed in haste. Thank you for entering this site as a room rather than a feed. May you find a line that rearranges your day by a millimeter; that is enough.',
];
